import os
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure the Gemini API
genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

# Define the reporting model (using Flash Lite for speed and quota stability)
REPORTING_MODEL_NAME = "gemini-3.1-flash-lite"

def generate_report(user_query: str, analysis_data: str) -> str:
    """
    Synthesizes raw market analysis data into a professional analyst report using the Gemini API.
    
    Parameters
    ----------
    user_query    : str — The original request from the user.
    analysis_data : str — The raw data or intermediate findings from the market collectors/scoring engine.
    
    Returns
    -------
    str — A formatted Markdown report.
    """
    
    system_instruction = """
    You are a Senior Market Intelligence Analyst. Your goal is to synthesize raw market data into 
    professional, data-driven, and actionable reports for product managers and developers.
    Your tone must be professional but accessible.
    """

    prompt = f"""
    {system_instruction}

    User Question: {user_query}

    Market Data & Analysis Summary:
    {analysis_data}

    Your report MUST follow this exact structure:
    
    # Market Intelligence Report
    
    ## Executive Summary
    (Summarize the high-level findings in 2-3 sentences)

    ## Mobile Apps Trends
    (Detail analysis for the non-gaming mobile app market)

    ## Mobile Games Trends
    (Detail analysis for the mobile gaming sector)

    ## PC Games Trends
    (Detail analysis for the Steam/PC gaming market)

    ## Cross-Platform Analysis
    (Identify overlaps, shared genres, or cross-platform migrations)

    ## Key Data Points
    (Extract and list at least 3 specific numeric values found in the data)

    ## Conclusion & Recommendations
    (Provide at least two actionable insights based on the data)
    
    ---
    *Generated by Market Intelligence Analyst AI*
    """

    try:
        model = genai.GenerativeModel(model_name=REPORTING_MODEL_NAME)
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        print(f"[ERROR] Gemini API failed during report generation: {e}")
        # Return a professional fallback template
        return f"""
# Market Intelligence Report (FALLBACK)

## Executive Summary
The requested report could not be fully generated due to a temporary service interruption.

## Current Market Status
**Data currently unavailable.** 

We are seeing high demand or technical limitations with the analysis engine. Please try your request again in a few minutes.

## Recommendations
- Check the connectivity to the database.
- Verify API key quotas for {REPORTING_MODEL_NAME}.

---
*Generated by Market Intelligence Analyst AI (Error Recovery Mode)*
"""

if __name__ == "__main__":
    # Dry-test with dummy data
    print("--- Starting Report Generator Dry-Test ---")
    
    dummy_query = "What is the state of the RPG genre across platforms?"
    dummy_data = """
    Mobile Games: 'Genshin Impact' has 5M+ reviews and rank 1 in RPG. 'Honkai: Star Rail' is rank 2.
    PC Games: 'Elden Ring' is a top seller on Steam with 95% positive sentiment. 'Baldur's Gate 3' continues to trend.
    Mobile Apps: Discord and Twitch (Gaming utilities) are seeing 15% growth in install counts this week.
    Trend Score: RPG Category Score = 0.88 (Strong growth).
    """
    
    report = generate_report(dummy_query, dummy_data)
    
    print("\n--- Generated Report Output ---\n")
    print(report)
    print("\n--- End of Output ---")
